stages:
  - validate
  - container

variables:
  DOCKER_DRIVER: overlay2

validate:
  stage: validate
  image: node:22-alpine
  script:
    - npm install --no-audit --no-fund
    - npm run build
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - .next/

container:
  stage: container
  image: docker:27
  services:
    - docker:27-dind
  script:
    - docker build -t sachin-das-portfolio:$CI_COMMIT_SHORT_SHA .
    - docker save sachin-das-portfolio:$CI_COMMIT_SHORT_SHA -o portfolio-image.tar
  artifacts:
    expire_in: 1 day
    paths:
      - portfolio-image.tar
